"""opportunity candidates

Revision ID: 0005_candidates
Revises: 0004_payments
Create Date: 2026-09-18 19:35:58.015927
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0005_candidates'
down_revision = '0004_payments'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_candidates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='candidatestatus', native_enum=False, length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['funding_opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_candidates_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_opportunity_candidates_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_opportunity_candidates_fingerprint'))

    op.drop_table('opportunity_candidates')
    # ### end Alembic commands ###
